// Package definitions — seeded to DB, also used for static display

export const PACKAGES = [
  {
    slug: "free",
    name: "Ücretsiz",
    description: "Başlamak için mükemmel",
    price: 0,
    yearlyPrice: 0,
    sortOrder: 0,
    isFeatured: false,
    videoPerMonth: 3,
    storageGb: 0.5,
    socialAccounts: 1,
    teamMembers: 1,
    maxVideoSeconds: 30,
    maxResolution: "720p",
    watermark: true,
    apiAccess: false,
    prioritySupport: false,
    customBranding: false,
    analyticsAccess: false,
    scheduledPosting: false,
    features: [
      "3 video / ay",
      "1 sosyal hesap",
      "500 MB depolama",
      "30 sn. maksimum video",
      "720p çözünürlük",
      "Filigran (watermark)",
    ],
  },
  {
    slug: "starter",
    name: "Başlangıç",
    description: "Bireysel içerik üreticiler için",
    price: 99,
    yearlyPrice: 890,
    sortOrder: 1,
    isFeatured: false,
    videoPerMonth: 20,
    storageGb: 5,
    socialAccounts: 5,
    teamMembers: 1,
    maxVideoSeconds: 60,
    maxResolution: "1080p",
    watermark: false,
    apiAccess: false,
    prioritySupport: false,
    customBranding: false,
    analyticsAccess: true,
    scheduledPosting: true,
    features: [
      "20 video / ay",
      "5 sosyal hesap",
      "5 GB depolama",
      "60 sn. maksimum video",
      "1080p çözünürlük",
      "Filigransız",
      "Zamanlı yayın",
      "Temel analitik",
    ],
  },
  {
    slug: "pro",
    name: "Profesyonel",
    description: "Ajanslar ve aktif içerik ekipleri için",
    price: 299,
    yearlyPrice: 2690,
    sortOrder: 2,
    isFeatured: true,
    videoPerMonth: -1,
    storageGb: 50,
    socialAccounts: 20,
    teamMembers: 5,
    maxVideoSeconds: 300,
    maxResolution: "4K",
    watermark: false,
    apiAccess: true,
    prioritySupport: false,
    customBranding: true,
    analyticsAccess: true,
    scheduledPosting: true,
    features: [
      "Sınırsız video",
      "20 sosyal hesap",
      "50 GB depolama",
      "5 dk. maksimum video",
      "4K çözünürlük",
      "API erişimi",
      "Özel marka (watermark)",
      "5 ekip üyesi",
      "Gelişmiş analitik",
      "Öncelikli destek",
    ],
  },
  {
    slug: "enterprise",
    name: "Kurumsal",
    description: "Büyük ekipler ve kurumsal kullanım",
    price: 999,
    yearlyPrice: 8990,
    sortOrder: 3,
    isFeatured: false,
    videoPerMonth: -1,
    storageGb: -1,
    socialAccounts: -1,
    teamMembers: -1,
    maxVideoSeconds: -1,
    maxResolution: "4K",
    watermark: false,
    apiAccess: true,
    prioritySupport: true,
    customBranding: true,
    analyticsAccess: true,
    scheduledPosting: true,
    features: [
      "Sınırsız video",
      "Sınırsız sosyal hesap",
      "Sınırsız depolama",
      "Sınırsız video uzunluğu",
      "4K çözünürlük",
      "Tam API erişimi",
      "Sınırsız ekip üyesi",
      "Özel entegrasyon",
      "SLA garantisi",
      "7/24 öncelikli destek",
      "Özel onboarding",
    ],
  },
] as const;

export type PackageSlug = (typeof PACKAGES)[number]["slug"];

export const ROLE_PERMISSIONS = {
  SUPER_ADMIN: ["*"],
  ADMIN: [
    "users:read", "users:write", "users:delete",
    "content:read", "content:write", "content:delete",
    "settings:read", "settings:write",
    "scraper:run", "publisher:run",
    "media:upload", "media:delete",
    "social:connect", "social:publish",
  ],
  EDITOR: [
    "content:read", "content:write",
    "media:upload",
    "scraper:run",
  ],
  PUBLISHER: [
    "content:read",
    "media:upload",
    "social:connect", "social:publish",
    "publisher:run",
  ],
  VIEWER: [
    "content:read",
    "media:read",
  ],
} as const;

export function hasPermission(
  role: keyof typeof ROLE_PERMISSIONS,
  permission: string
): boolean {
  const perms = ROLE_PERMISSIONS[role] as readonly string[];
  return perms.includes("*") || perms.includes(permission);
}
